name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name   : test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run : sudo apt-get update && sudo apt install libgtest-dev g++ cmake valgrind
   
    - name: Create estl test build directory
      run:  sudo mkdir estl/test/build
    
    - name: Create kernel test build directory
      run:  sudo mkdir kernel/test/build
    
    - name: Build-estl-test
      working-directory: ./estl/test/build
      run: sudo cmake .. && sudo make -j ${proc}

    - name: Build-kernel-test
      working-directory: ./kernel/test/build
      run: sudo cmake .. && sudo make -j ${proc}

    - name: Test-estl
      working-directory: ./estl/test/build
      run: sudo make test
    
    - name: Test-kernel
      working-directory: ./kernel/test/build
      run: sudo make test
